apiVersion: v2
name: kubegres
description:  Kubernetes operator allowing to deploy one or many clusters of PostgreSql instances with data replication and failover enabled out-of-the box

#home: The URL of this projects home page (optional)
home: https://www.pzetatouch.it

#  - A list of URLs to source code for this project (optional)
sources:
  - https://github.com/punga78/kubegreshelm

#icon: A URL to an SVG or PNG image to be used as an icon (optional).
icon: https://www.kubegres.io/includes/img/kubegresLogo.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# The optional kubeVersion field can define semver constraints on supported Kubernetes versions.
# Helm will validate the version constraints when installing the chart and fail if the cluster
# runs an unsupported Kubernetes version.
# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
kubeVersion: ">= 1.20.0-0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
#appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
appVersion: "1.16.0"

#  - A list of keywords about this project (optional)
keywords:
    - kubegres
    - postgres
urls:
    - https://github.com/punga78/kubegreshelm/releases/download/kubegres-0.1.3/kubegres-0.1.3.tgz
#sources:
#dependencies: # A list of the chart requirements (optional)
#  - name: The name of the chart (nginx)
#    version: The version of the chart ("1.2.3")
#    repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
#    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
#    tags: # (optional)
#      - Tags can be used to group charts for enabling/disabling together
#    import-values: # (optional)
#      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
#    alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: "Luca Zanni"
    #email: info@pzeta.it
#    url: A URL for the maintainer (optional for each maintainer)
#deprecated: Whether this chart is deprecated (optional, boolean)

#annotations:
#  example: A list of annotations keyed by name (optional).
annotations:
  artifacthub.io/changes: |
    - "helm: Fix opentelemetry module installation for daemonset (#9792)"
    - "Update charts/* to keep project name display aligned (#9931)"
    - "Update Ingress-Nginx version controller-v1.8.0"
  artifacthub.io/prerelease: "false"