{{if .Values.backup.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-bk
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.size }}

{{end}}
