apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres-{{ include "kubegres.fullname" . }}
  namespace: {{ .Release.Name }}
  annotations:
    imageregistry: "https://hub.docker.com/"
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
   replicas: {{ .Values.replicaCount }}
   image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
   imagePullPolicy: {{ .Values.image.pullPolicy }}
   port: {{ .Values.service.port }}

   database:
      size: {{ .Values.database.size }}
      storageClassName: local-storage
      volumeMount: /var/lib/postgresql/data
     
   customConfig: postgres-config

   resources:
      {{- toYaml .Values.resources | nindent 12 }}
   probe:
      livenessProbe:
         exec:
            command:
              - sh
              - -c
              - exec pg_isready -U postgres -h $POD_IP
         failureThreshold: 10
         initialDelaySeconds: 60
         periodSeconds: 20
         successThreshold: 1
         timeoutSeconds: 15

      readinessProbe:
         exec:
            command:
              - sh
              - -c
              - exec pg_isready -U postgres -h $POD_IP
         failureThreshold: 3
         initialDelaySeconds: 5
         periodSeconds: 5
         successThreshold: 1
         timeoutSeconds: 3

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: replicationUserPassword