apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{ .Release.Name }}-secret
  namespace: {{ .Release.Name }}
type: Opaque
stringData:
  superUserPassword: {{ .Values.superUserPassword }}
  replicationUserPassword: {{ .Values.replicationUserPassword }}