apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubegres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  superUserPassword: {{ .Values.superUserPassword }}
  replicationUserPassword: {{ .Values.replicationUserPassword }}