{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubegres.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubegres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: pg
  selector:
    app: {{ .Release.Name }}
    replicationRole: primary
{{- end }}